# fly.toml app configuration file generated for reesep-com-test on 2023-06-29T12:45:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reesep-com-test"
primary_region = "sea"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
